#!/usr/bin/env python3
"""
Send email alert when a new article is published.
Usage: python3 send_alert.py "Article Title" "filename.html"
Pure SMTP — no MCP, no Gmail API, no inbox access.
"""
import sys
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

# === CONFIGURATION ===
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SENDER_EMAIL = "articlealrert@gmail.com"
SENDER_PASSWORD = "ocun hwee yacq fqwb"  # Gmail App Password (not regular password)

RECIPIENTS = [
    "chatgptkrylor@gmail.com",
    "articlealrert@gmail.com",
]

BASE_URL = "https://chatgptkrylor.github.io/ai-artical-pages/articles"


def send_alert(title: str, filename: str):
    article_url = f"{BASE_URL}/{filename}"
    now = datetime.now().strftime("%B %d, %Y at %I:%M %p")

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"New Article Published: {title}"
    msg["From"] = f"Optimus The Articale maker <{SENDER_EMAIL}>"
    msg["To"] = ", ".join(RECIPIENTS)

    text = f"""New Article Published

Title: {title}
URL: {article_url}
Published: {now}

— Optimus The Articale makerScribe Agent
"""

    html = f"""<!DOCTYPE html>
<html>
<head>
  <style>
    body {{ font-family: 'Segoe UI', sans-serif; background: #faf9f7; padding: 40px 20px; margin: 0; }}
    .card {{ max-width: 560px; margin: 0 auto; background: #1a1a2e; border-radius: 14px; overflow: hidden; }}
    .header {{ padding: 28px 32px 20px; }}
    .dot {{ display: inline-block; width: 8px; height: 8px; border-radius: 50%; background: #e85d26; margin-right: 8px; vertical-align: middle; }}
    .brand {{ color: rgba(255,255,255,0.5); font-size: 12px; letter-spacing: 1.5px; text-transform: uppercase; vertical-align: middle; }}
    .body {{ padding: 0 32px 32px; }}
    .label {{ color: #e85d26; font-size: 11px; font-weight: 600; letter-spacing: 1.5px; text-transform: uppercase; margin-bottom: 12px; }}
    h1 {{ color: #ffffff; font-size: 22px; font-weight: 600; line-height: 1.3; margin: 0 0 16px; }}
    .meta {{ color: rgba(255,255,255,0.4); font-size: 13px; margin-bottom: 24px; }}
    .btn {{ display: inline-block; background: #e85d26; color: #ffffff; text-decoration: none; padding: 12px 28px; border-radius: 8px; font-size: 14px; font-weight: 600; }}
    .footer {{ padding: 20px 32px; border-top: 1px solid rgba(255,255,255,0.08); }}
    .footer p {{ color: rgba(255,255,255,0.25); font-size: 12px; margin: 0; }}
  </style>
</head>
<body>
  <div class="card">
    <div class="header">
      <span class="dot"></span>
      <span class="brand">Email Marketing Intelligence</span>
    </div>
    <div class="body">
      <div class="label">New Article Published</div>
      <h1>{title}</h1>
      <div class="meta">{now}</div>
      <a href="{article_url}" class="btn">Read Article &rarr;</a>
    </div>
    <div class="footer">
      <p>Automatically generated by Scribe Agent &middot; Powered by OpenClaw</p>
    </div>
  </div>
</body>
</html>"""

    msg.attach(MIMEText(text, "plain"))
    msg.attach(MIMEText(html, "html"))

    try:
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            server.starttls()
            server.login(SENDER_EMAIL, SENDER_PASSWORD)
            server.sendmail(SENDER_EMAIL, RECIPIENTS, msg.as_string())
        print(f"Alert sent to {', '.join(RECIPIENTS)}")
    except Exception as e:
        print(f"Email alert failed: {e}", file=sys.stderr)


if __name__ == "__main__":
    title = sys.argv[1] if len(sys.argv) > 1 else "Untitled Article"
    filename = sys.argv[2] if len(sys.argv) > 2 else "unknown.html"
    send_alert(title, filename)